name: "Report deployment status to Slack"
inputs:
  project:
    description: "The name of the project."
    required: true
  tag:
    description: "The name of the branch or tag."
    required: true
  environment:
    description: "The name of the environment."
    required: true
  slack-channel:
    description: "The name of the slack channel."
    required: true
    default: team-eng-qa-devops
  event:
    description: "Deployment event type. Possible values are start, success, or failure."
    required: true
  url:
    description: "Deployment event type. Possible values are start, success, or failure."
    required: false
    default: ${{ github.event.deployment_status.target_url }}
  AZURE_KV_CI_SERVICE_PRINCIPAL:
    description: "The service principal used to authenticate to Azure."
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to Azure - Prod Subscription
      uses: Azure/login@4c88f01b0e3a5600e08a37889921afd060f75cf0 # v1.5.0
      with:
        creds: ${{ inputs.AZURE_KV_CI_SERVICE_PRINCIPAL }}

    - name: Retrieve slack secrets
      id: retrieve-slack-secrets
      uses: bitwarden/gh-actions/get-keyvault-secrets@master
      with:
        keyvault: bitwarden-ci
        secrets: "slack-bot-token"

    - name: Get slack message
      shell: bash
      id: get-slack-message
      env:
        EVENT: ${{ inputs.event }}
      run: |
        case $EVENT in
          start)
            MESSAGE=":loading: Updating ${{ inputs.environment }} to `${{ inputs.tag }}` on [${{ inputs.project }}](${{ inputs.url }})."
            ;;
          success)
            MESSAGE=":white_check_mark: Updated ${{ inputs.environment }} to `${{ inputs.tag }}` on ${{ inputs.project }}."
            ;;
          failure)
            MESSAGE=":x: Failed to update ${{ inputs.environment }} to `${{ inputs.tag }}` on ${{ inputs.project }}.\nPlease retry or contact @devops team."
            ;;
        esac

        echo "message=$MESSAGE" >> $GITHUB_OUTPUT

    - name: Post to a Slack channel on ${{ inputs.event }}
      uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
      with:
        channel-id: ${{ inputs.slack-channel }}
        slack-message: ${{ steps.run_tests.outputs.message }}
      env:
        SLACK_BOT_TOKEN: ${{ steps.retrieve-slack-secrets.outputs.slack-bot-token }}
