name: "Report deployment status to Slack"
description: "Report deployment status to Slack"
inputs:
  project:
    description: "The name of the project."
    required: true
  tag:
    description: "The name of the branch or tag."
    required: true
  commit-sha:
    description: "The SHA of the branch or tag."
    required: true
  db_migration_detected:
    description: "Whether a database migration was detected."
    required: false
    default: false
  environment:
    description: "The name of the environment."
    required: true
  update-ts:
    description: "Message ID to update in Slack channel."
    required: false
  event:
    description: "Deployment event type. Possible values are start, success, or failure."
    required: true
  url:
    description: "Deployment event type. Possible values are start, success, or failure."
    required: false
    default: ${{ github.event.deployment_status.target_url }}
  AZURE_KV_CI_SERVICE_PRINCIPAL:
    description: "The service principal used to authenticate to Azure."
    required: true
outputs:
  ts:
    description: "Message ID of the Slack message"
    value: ${{ steps.slack-message.outputs.ts }}

runs:
  using: "composite"
  steps:
    - name: Login to Azure - Prod Subscription
      uses: Azure/login@e15b166166a8746d1a47596803bd8c1b595455cf # v1.6.0
      with:
        creds: ${{ inputs.AZURE_KV_CI_SERVICE_PRINCIPAL }}

    - name: Retrieve Slack secrets
      id: retrieve-slack-secrets
      uses: bitwarden/gh-actions/get-keyvault-secrets@main
      with:
        keyvault: bitwarden-ci
        secrets: "slack-bot-token"

    - name: Slack message setup
      id: setup
      shell: bash
      run: |
        function slack_message_fn () {
          local event="${{ inputs.event }}"
          local environment="${{ inputs.environment }}"
          local tag="${{ inputs.tag }}"
          local project="${{ inputs.project }}"
          local url="${{ inputs.url }}"
          local commit_sha="${{ inputs.commit-sha }}"

          case $event in
            start)
              SLACK_MESSAGE=":loading: Deploying \`$tag\` to $environment on $project.
              $url
              SHA: \`$commit_sha\`"
              ;;

            success)
              SLACK_MESSAGE=":white_check_mark: Deployed \`$tag\` to $environment on $project.
              $url
              SHA: \`$commit_sha\`"
              ;;

            failure)
              SLACK_MESSAGE=":x: Failed to deploy \`$tag\` to $environment on $project.
              $url
              SHA: \`$commit_sha\`
              Please retry or contact @devops team."
              ;;

            cancelled)
              SLACK_MESSAGE=":hand: Cancelled deploy of \`$tag\` to $environment on $project.
              $url
              SHA: \`$commit_sha\`"
              ;;

            no-changes)
              SLACK_MESSAGE=":heavy_minus_sign: No changes were made for \`$tag\` deployment to $environment on $project.
              $url
              SHA: \`$commit_sha\`"
              ;;
          esac
        }

        if [[ ${{ inputs.db_migration_detected }} == true && ${{ inputs.tag }} != main && ${{ inputs.tag }} != rc && ${{ inputs.tag }} != hotfix-rc ]]; then
          slack_message_fn
          SLACK_MESSAGE="$SLACK_MESSAGE
          :red_siren: This branch has new database migration changes."
        else
          slack_message_fn
        fi

        echo 'slack_message<<EOF' >> $GITHUB_OUTPUT
        echo "$SLACK_MESSAGE" >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    - name: Determine Slack Channel ID
      id: slack-channel
      shell: bash
      env:
        DEPLOYMENT_ENV: ${{ inputs.environment }}
      run: |
        case $DEPLOYMENT_ENV in
          "US-QA Cloud"|"EU-QA Cloud")
            echo "channel_id=alerts-deploy-qa" >> $GITHUB_OUTPUT
            ;;
          "US-DEV Cloud"|"EU-DEV Cloud")
            echo "channel_id=alerts-deploy-dev" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "channel_id=devops-alerts-test" >> $GITHUB_OUTPUT
            ;;
        esac

    - name: Post/Edit message to a Slack channel
      id: slack-message
      uses: slackapi/slack-github-action@6c661ce58804a1a20f6dc5fbee7f0381b469e001 # v1.25.0
      with:
        channel-id: ${{ steps.slack-channel.outputs.channel_id }}
        slack-message: ${{ steps.setup.outputs.slack_message }}
        update-ts: ${{ inputs.update-ts }}
      env:
        SLACK_BOT_TOKEN: ${{ steps.retrieve-slack-secrets.outputs.slack-bot-token }}
