name: "Report deployment status to Slack"
description: "Report deployment status to Slack"
inputs:
  project:
    description: "The name of the project."
    required: true
  tag:
    description: "The name of the branch or tag."
    required: true
  commit-sha:
    description: "The SHA of the branch or tag."
    required: true
  environment:
    description: "The name of the environment."
    required: true
  slack-channel:
    description: "The name of the Slack channel."
    default: team-eng-qa-devops
  update-ts:
    description: "Message ID to update in Slack channel."
    required: false
  event:
    description: "Deployment event type. Possible values are start, success, or failure."
    required: true
  url:
    description: "Deployment event type. Possible values are start, success, or failure."
    required: false
    default: ${{ github.event.deployment_status.target_url }}
  AZURE_KV_CI_SERVICE_PRINCIPAL:
    description: "The service principal used to authenticate to Azure."
    required: true
outputs:
  channel_id:
    description: "Channel ID where the Slack message was posted"
    value: ${{ steps.slack-message.outputs.channel_id }}
  ts:
    description: "Message ID of the Slack message"
    value: ${{ steps.slack-message.outputs.ts }}

runs:
  using: "composite"
  steps:
    - name: Login to Azure - Prod Subscription
      uses: Azure/login@e15b166166a8746d1a47596803bd8c1b595455cf # v1.6.0
      with:
        creds: ${{ inputs.AZURE_KV_CI_SERVICE_PRINCIPAL }}

    - name: Retrieve Slack secrets
      id: retrieve-slack-secrets
      uses: bitwarden/gh-actions/get-keyvault-secrets@main
      with:
        keyvault: bitwarden-ci
        secrets: "slack-bot-token"

    - name: Slack message setup
      id: setup
      shell: bash
      run: |
        case "${{ inputs.event }}" in
          start)
            SLACK_MESSAGE=":loading: Updating ${{ inputs.environment }} to \`${{ inputs.tag }}\` on ${{ inputs.project }}.
            ${{ inputs.url }}
            SHA: \`${{ inputs.commit-sha }}\`"
            ;;

          success)
            SLACK_MESSAGE=":white_check_mark: Updated ${{ inputs.environment }} to \`${{ inputs.tag }}\` on ${{ inputs.project }}.
            ${{ inputs.url }}
            SHA: \`${{ inputs.commit-sha }}\`"
            ;;

          failure)
            SLACK_MESSAGE=":x: Failed to update ${{ inputs.environment }} to \`${{ inputs.tag }}\` on ${{ inputs.project }}.
            ${{ inputs.url }}
            SHA: \`${{ inputs.commit-sha }}\`
            Please retry or contact @devops team."
            ;;

          cancelled)
            SLACK_MESSAGE=":hand: Cancelled update of ${{ inputs.environment }} to \`${{ inputs.tag }}\` on ${{ inputs.project }}.
            ${{ inputs.url }}
            SHA: \`${{ inputs.commit-sha }}\`"
            ;;
        esac

        echo 'slack_message<<EOF' >> $GITHUB_OUTPUT
        echo "$SLACK_MESSAGE" >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    - name: Post/Edit message to a Slack channel
      id: slack-message
      uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
      with:
        channel-id: ${{ inputs.slack-channel }}
        slack-message: ${{ steps.setup.outputs.slack_message }}
        update-ts: ${{ inputs.update-ts }}
      env:
        SLACK_BOT_TOKEN: ${{ steps.retrieve-slack-secrets.outputs.slack-bot-token }}
