name: "Report deployment status to Slack"
description: "Report deployment status to Slack"
inputs:
  project:
    description: "The name of the project."
    required: true
  tag:
    description: "The name of the branch or tag."
    required: true
  environment:
    description: "The name of the environment."
    required: true
  slack-channel:
    description: "The name of the Slack channel."
    default: team-eng-qa-devops
  update-ts:
    description: "Message ID to update in Slack channel."
    required: false
  event:
    description: "Deployment event type. Possible values are start, success, or failure."
    required: true
  url:
    description: "Deployment event type. Possible values are start, success, or failure."
    required: false
    default: ${{ github.event.deployment_status.target_url }}
  AZURE_KV_CI_SERVICE_PRINCIPAL:
    description: "The service principal used to authenticate to Azure."
    required: true
outputs:
  channel_id:
    description: "Channel ID where the Slack message was posted"
    value: ${{ steps.slack-message.outputs.channel_id }}
  ts:
    description: "Message ID of the Slack message"
    value: ${{ steps.slack-message.outputs.ts }}

runs:
  using: "composite"
  steps:
    - name: Login to Azure - Prod Subscription
      uses: Azure/login@de95379fe4dadc2defb305917eaa7e5dde727294 # v1.5.1
      with:
        creds: ${{ inputs.AZURE_KV_CI_SERVICE_PRINCIPAL }}

    - name: Retrieve Slack secrets
      id: retrieve-slack-secrets
      uses: bitwarden/gh-actions/get-keyvault-secrets@main
      with:
        keyvault: bitwarden-ci
        secrets: "slack-bot-token"

    - name: Slack message setup
      id: setup
      shell: bash
      run: |
        case "${{ inputs.event }}" in
          start)
            SLACK_MESSAGE=':loading: Updating ${{ inputs.environment }} to `${{ inputs.tag }}` on ${{ inputs.project }}.\n${{ inputs.url }}.'
            ;;

          success)
            SLACK_MESSAGE=':white_check_mark: Updated ${{ inputs.environment }} to `${{ inputs.tag }}` on ${{ inputs.project }}.\n${{ inputs.url }}.'
            ;;
        
          failure)
            SLACK_MESSAGE=':x: Failed to update ${{ inputs.environment }} to `${{ inputs.tag }}` on ${{ inputs.project }}.\n${{ inputs.url }}.\nPlease retry or contact @devops team.'
            ;;
        esac

        echo "slack_message=$SLACK_MESSAGE" >> $GITHUB_OUTPUT

    - name: Post message to a Slack channel
      id: slack-message
      uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
      with:
        channel-id: ${{ inputs.slack-channel }}
        slack-message: ${{ steps.setup.outputs.slack_message }}
        update-ts: ${{ inputs.update-ts }}
      env:
        SLACK_BOT_TOKEN: ${{ steps.retrieve-slack-secrets.outputs.slack-bot-token }}
