name: 'Lint Workflow'
description: 'Lints GitHub Actions Workflow'
inputs:
  workflows:
    description: "Path to workflow file(s)"
    required: true
runs:
  using: "composite"
  steps:
    - run: pip install --user yamllint
      shell: bash
    - run: python ${{ github.action_path }}/lint.py "${{ inputs.workflows }}"
      shell: bash
    - run: |
        TRIM_PATH=$(echo ${{ inputs.workflows }} | tr '\n' ' ')
        yamllint -f colored -c ${{ github.action_path }}/.yamllint.yml $TRIM_PATH
      shell: bash
      working-directory: ${{ github.workspace }}
