name: 'Lint Workflow'
description: 'Lints GitHub Actions Workflow'
inputs:
  workflows:
    description: "Path to workflow file(s)"
    required: true
runs:
  using: "composite"
  steps:
    - run: pip install --user yamllint
      shell: bash
    - run: python ${{ github.action_path }}/lint.py "${{ inputs.workflows }}"
      shell: bash
    - run: yamllint -f colored -c ${{ github.action_path }}/.yamllint.yml "${{ inputs.workflows }}"
      shell: bash
