name: 'Lint Workflow'
description: 'Lints GitHub Actions Workflow'
inputs:
  workflows:
    description: "Path to workflow file(s)"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: pip install --user yamllint
      shell: bash

    - name: Setup
      id: setup 
      run: |
        FORMAT_PATH=$(echo ${{ inputs.workflows }} | tr '\n' ' ')
        echo "::set-output name=path::$FORMAT_PATH"
      shell: bash

    - name: Python lint
      run: python ${{ github.action_path }}/lint.py "${{ steps.setup.outputs.path }}"
      shell: bash

    - name: YAML lint
      run: yamllint -f colored -c ${{ github.action_path }}/.yamllint.yml "${{ steps.setup.outputs.path }}"
      shell: bash
      working-directory: ${{ github.workspace }}
