name: "Install Azure Sign Tool"
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Check Runner OS
      shell: bash
      run: |
        if ["$RUNNER_OS" != "Windows"]; then
          echo "[!] This workflow only supports Windows runners"
          exit 1
        fi

    - name: Set up dotnet
      uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3.2.0  
      with:
        dotnet-version: "6.0.x"

    - name: Install AST
      shell: pwsh
      env:
        AST_PINNED_COMMIT: "9f30f7a267eff7f3fe494c49e5a536a337c8dfde" # v4.0.1
      run: |
        cd $HOME

        git clone https://github.com/vcsjones/AzureSignTool.git
        cd AzureSignTool
        git switch --detach $env:AST_PINNED_COMMIT
        $pinned_short_commit = $env:AST_PINNED_COMMIT[0..9] -join ""
        $ast_version = "0.0.0-g$pinned_short_commit"

        Write-Host "--------"
        Write-Host "pinned git commit - $env:AST_PINNED_COMMIT"
        Write-Host "pinned short git commit - $pinned_short_commit"
        Write-Host "PACKAGE VERSION TO BUILD - $ast_version"
        Write-Host "--------"

        dotnet restore
        dotnet pack --output ./nupkg
        dotnet tool install --global --ignore-failed-sources --add-source ./nupkg --version $ast_version azuresigntool
