name: "PLIST/XML/JSON Version Bump"
description: "Replaces versions in PLIST/JSON/XML for easier version updating."
author: "Bitwarden"
branding:
  icon: download
  color: blue
inputs:
  version:
    description: "New version to use."
    required: false
  file_path:
    description: "Path to the file to apply the new version."
    required: true
outputs:
  status:
    description: "Status"
  version:
    description: "New Version"
runs:
  using: "docker"
  image: "Dockerfile"