name: "Version Check"
description: "Checks to make sure the version matches the correct format"
inputs:
  version:
    description: 'Version string to check'
    required: true
runs:
  using: "composite"
  steps:
    - name: Check Runner OS
      shell: bash
      env:
        RUNNER_OS: ${{ runner.os }}
      run: |
        if [ "$RUNNER_OS" != "Linux" ]; then
          echo "[!] This workflow only supports Linux runners"
          exit 1
        fi

    - name: Check version format
      id: check-version-format
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: |
        if [[ "$VERSION" =~ ^20[0-9]{2}\.(1[0-2]|[1-9])\.[0-9]+$ ]]; then
          echo "Version input validation successful."
          exit 0
        else
          echo "Version input validation failed."
          exit 1
        fi