---

name: CI-Lint

on:
  push:
    paths:
      - "lint-workflow/**"

jobs:
  CI:
    name: CI
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Set up Python
        uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pyyaml urllib3
      - name: Test lint
        run: pytest tests
        working-directory: lint-workflow
