---

name: CI-Lint

on:
  push:
    paths:
      - "lint-workflow/**"
  workflow_dispatch: {}

jobs:
  CI:
    name: CI
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: "3.9"

      - name: Install dependencies
        working-directory: lint-workflow
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Test lint
        working-directory: lint-workflow
        run: pipenv run pytest tests

      - uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0
      - uses: bitwarden/gh-actions/crowdin@ca4bf694de171425dd5ace89611e18f738b822b8