---

name: CI-Lint

on:
  push:
    paths:
      - "lint-workflow/**"
  workflow_dispatch: {}

jobs:
  CI:
    name: CI
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Set up Python
        uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984
        with:
          python-version: "3.9"

      - name: Install dependencies
        working-directory: lint-workflow
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Test lint
        working-directory: lint-workflow
        run: pipenv run pytest tests
