---

name: CI-Lint

on:
  push:
    paths:
      - "lint-workflow/**"
  workflow_dispatch: {}

jobs:
  CI:
    name: CI
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Set up Python
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v2.3.1
        with:
          python-version: "3.9"

      - name: Install dependencies
        working-directory: lint-workflow
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Test lint
        working-directory: lint-workflow
        run: pipenv run pytest tests
