---

name: CI-Lint

on:
  push:
    paths:
      - "lint-workflow/**"
  workflow_dispatch: {}

jobs:
  CI:
    name: CI
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up Python
        uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # v4.6.1
        with:
          python-version: "3.9"

      - name: Install dependencies
        working-directory: lint-workflow
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Test lint
        working-directory: lint-workflow
        run: pipenv run pytest tests
