---

name: CI-Lint

on:
  push:
    paths:
      - "lint-workflow/**"
  workflow_dispatch: {}

jobs:
  CI:
    name: CI
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Set up Python
        uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984
        with:
          python-version: "3.9"

      - name: Install dependencies
        working-directory: lint-workflow
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install

      - name: Test lint
        working-directory: lint-workflow
        run: pytest tests
