---
name: Test report-upcoming release version to Slack
on:
  pull_request:
      paths:
      - "report-upcoming-release-version/**"
      - ".github/workflows/test-report-upcoming-release-version.yml"

jobs:
  test-report-upcoming-release-version:
    name: Test report upcoming release version to Slack
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Report upcoming release version to Slack
        uses: ./report-deployment-status-to-slack
        with:
          project: bitwarden/server
          version: upcoming_version
          slack-channel: devops-alerts-test
          AZURE_KV_CI_SERVICE_PRINCIPAL: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}
