---
name: Test - Get PR ID

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/_get_pr_id.yml
      - .github/workflows/test_get_pr_id.yml

jobs:
  pr:
    uses: .github/workflows/_get_pr_id.yml
    with:
      repository: "bitwarden/gh-actions"
      commit-sha: "7d46c75af91adbfdfc70689f4d8b3405b26bda6b"

  test_pr:
    name: Test Get PR ID
    runs-on: ubuntu-22.04
    needs:
      - pr
    steps:
      - name: Assert PR ID
        env:
          ID: ${{ needs.pr.outputs.id }}
        run: |
          if [[ "$ID" != "196" ]]; then
            exit 1
          fi

          exit 0
