---
name: Test report-upcoming release version to Slack
on:
  pull_request:
      paths:
      - "report-upcoming-release-version/**"
      - ".github/workflows/test-report-upcoming-release-version.yml"

jobs:
  test-report-upcoming-release-version:
    name: Test report upcoming release version to Slack
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Report upcoming release version to Slack
        uses: ./report-upcoming-release-version
        with:
          project: bitwarden/server
          version: upcoming_version
          slack-channel: bre-alerts-test
          AZURE_KV_CI_SERVICE_PRINCIPAL: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}
