---
name: Test Lint Workflow Action

on:
  pull_request:
    paths:
      - "lint-workflow"
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  test-lint-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Get workflow list
        id: workflow-list
        run: |
          WORKFLOW_LIST=$(ls .github/workflows | xargs -I {} echo -n ".github/workflows/{} ")
          echo "workflow-list=$WORKFLOW_LIST" >> $GITHUB_OUTPUT

      - uses: ./lint-workflow
        with:
          workflows: ${{ steps.workflow-list.outputs.workflow-list }}
