---
name: Upload Test Artifacts

on:
  workflow_dispatch:
    inputs: {}
  push:
    paths:
      - "download-artifacts/**"

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-20.04
    steps:
      - name: Dump
        run: |
          mkdir artifact
          echo $GITHUB_SHA > artifact/sha

      - name: Upload
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
        with:
          name: artifact
          path: artifact


  upload-multiple:
    name: Upload Multiple
    runs-on: ubuntu-20.04
    steps:
      - name: Dump
        run: |
          mkdir artifact1 artifact2
          echo $GITHUB_SHA > artifact1/sha1
          echo $GITHUB_SHA > artifact2/sha2

      - name: Upload first
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: artifact1
          path: artifact1

      - name: smt
        uses: bitwarden/gh-actions/.github/workflows/workflow-linter.yml@4f2a18ff6b521dbdc0d9079e528bf82114175520

      - name: Upload second
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
        with:
          name: artifact2
          path: artifact2


  upload-multiple-wildcard-test:
    name: Upload Multiple Wildcard Test
    runs-on: ubuntu-20.04
    steps:
      - name: Dump
        run: |
          mkdir artifact1 artifact2
          echo $GITHUB_SHA > artifact1/sha1
          echo $GITHUB_SHA > artifact2/sha2

      - name: Upload first
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
        with:
          name: artifact1.txt
          path: artifact1

      - name: Upload second
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
        with:
          name: artifact2.txt
          path: artifact2
