---
name: Upload Test Artifacts

on:
  workflow_dispatch:
    inputs: {}
  push:
    paths:
      - "download-artifacts/**"

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-22.04
    steps:
      - name: Dump
        run: |
          mkdir artifact
          echo $GITHUB_SHA > artifact/sha

      - name: Upload
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: artifact
          path: artifact


  upload-multiple:
    name: Upload Multiple
    runs-on: ubuntu-22.04
    steps:
      - name: Dump
        run: |
          mkdir artifact1 artifact2
          echo $GITHUB_SHA > artifact1/sha1
          echo $GITHUB_SHA > artifact2/sha2

      - name: Upload first
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: artifact1
          path: artifact1

      - name: Upload second
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: artifact2
          path: artifact2


  upload-multiple-wildcard-test:
    name: Upload Multiple Wildcard Test
    runs-on: ubuntu-22.04
    steps:
      - name: Dump
        run: |
          mkdir artifact1 artifact2
          echo $GITHUB_SHA > artifact1/sha1
          echo $GITHUB_SHA > artifact2/sha2

      - name: Upload first
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: artifact1.txt
          path: artifact1

      - name: Upload second
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: artifact2.txt
          path: artifact2
