---
name: Workflow Linter

on:
  pull_request:
    paths:
      - .github/workflows/**
  workflow_call:

jobs:
  lint:
    name: "Workflow Linter"
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Branch
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          fetch-depth: 0
          

      - name: TEST - View files
        run: ls -la .github/workflows

      - name: Changed files
        run: |
          git diff --name-only ${{ github.event.before }}..${{ github.event.after }}

      - name: Workflow Lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: bitwarden/gh-actions/lint-workflow@676ae4100b19625c0b0b70525e6c0181bd2d405f
