---
name: Workflow Linter

on:
  pull_request:
    paths:
      - .github/workflows/**
  workflow_call:

jobs:
  lint:
    name: "Workflow Linter"
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout Branch
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          fetch-depth: 0
          
      - name: Files to lint
        run: |
          files=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})
          echo $files
          

      - name: Workflow Lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: contains($(git diff --name-only ${{ github.event.before }}..${{ github.event.after }}), 'workflows')
        uses: bitwarden/gh-actions/lint-workflow@7b3fd93e0f1376e7b177205fb0df1370f11415a4
        with:
          workflows: $(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})
