---
name: Workflow Linter

on:
  pull_request:
    paths:
      - .github/workflows/**
  workflow_call:

jobs:
  lint:
    name: "Workflow Linter"
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Branch
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b'
        with:
          fetch-depth: 2

      - name: Get changed workflows
        id: changed-workflows
        run: |
          MODIFIED_WORKFLOWS=$(git diff --name-only HEAD | grep -E '.github/workflows/.*.yml' | tr )
          echo "::set-output name=modified-workflows::$MODIFIED_WORKFLOWS"

      - name: Workflow Lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: bitwarden/gh-actions/lint-workflow@feature/workflow-selective-linting
        with:
          workflows: ${{ steps.changed-workflows.outputs.modified-workflows }}
