---
name: Lint workflow

on:
  workflow_dispatch:
    
jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Test
        run: |
          echo "${{ contains(github.event.*.labels.*.name, 'hold') }}"
