---
name: Workflow Linter

on:
  pull_request:
    paths:
      - .github/workflows/**
  workflow_call:

jobs:
  lint:
    name: "Workflow Linter"
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout Full History
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0

      - name: Check for changed workflows
        id: changes
        run: |
          changes=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})
          if [[ $changes == *"workflows"* ]]; then
            echo "::set-output name=workflows_changed::true"
          fi

      - name: Workflow Lint
        if: workflows_changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: bitwarden/gh-actions/lint-workflow@7bdcb9d0dbd4851a7225319fb962fa7bdd45bba9
        with:
          workflows: $(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})